apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: devops-demo
  labels:
    app.kubernetes.io/name: devops-demo
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: devops-demo-secrets
  namespace: devops-demo
  labels:
    app.kubernetes.io/name: devops-demo
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: devops-demo-secrets
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: devops-demo
        property: API_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: devops-demo
        property: DB_PASSWORD
