# Dev environment overrides
replicaCount: 1

image:
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: false

config:
  NODE_ENV: "development"
  LOG_LEVEL: "debug"

ingress:
  hosts:
    - host: devops-demo.dev.local
      paths:
        - path: /
          pathType: Prefix

networkPolicy:
  enabled: false
