{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "devops-demo.fullname" . }}-vault-backend
  labels:
    {{- include "devops-demo.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.externalSecrets.vaultServer | quote }}
      path: {{ .Values.externalSecrets.vaultPath | quote }}
      version: {{ .Values.externalSecrets.vaultVersion | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.externalSecrets.tokenSecretName | quote }}
          key: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "devops-demo.fullname" . }}-secrets
  labels:
    {{- include "devops-demo.labels" . | nindent 4 }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ include "devops-demo.fullname" . }}-vault-backend
    kind: SecretStore
  target:
    name: {{ include "devops-demo.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.externalSecrets.remoteSecretKey | quote }}
        property: {{ . }}
    {{- end }}
{{- end }}
